# Numpy

In [8]:
import numpy as np

# Create One Dimension Array

In [9]:
one_dim_array = np.array([1,2,3,4])
one_dim_array

array([1, 2, 3, 4])

# Create Two Dimension Array

In [10]:
two_dim_array = np.array([[1,2,3],[4,5,6]])
two_dim_array

array([[1, 2, 3],
       [4, 5, 6]])

# Get Dimension of Array

In [11]:
two_dim_array.ndim

2

# Get Size of Array

In [12]:
two_dim_array.size

6

# Get Shape of Array

In [6]:
two_dim_array.shape

(2, 3)

# What is difference between dimension, size and shape of numpy array?

## `ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

## `ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

## `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, here in the above example, we have 2D array with 2 rows and 3 columns which means the shape would be (2,3) 

### Here, the `shape` returns a tupple which means we can get rows and columns of an array by tupple assignment

In [7]:
rows, columns = two_dim_array.shape
columns 

3

### One thing to note is that there is basic difference between python list and numpy
### In python, everything is object even list too. Which results in more memory. Where as numpy stores the elements in contigious memory address just like C. Also, numpy only allows homogeneous data
### More difference can be found [here](https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)

## Get itemsize of numpy array

In [8]:
one_dim_array.itemsize

8

In [9]:
one_dim_array.dtype

dtype('int64')

### Complex numbers plays pivotal role in mathematical computation.Numpy allows to create arrays with numpy data type

In [10]:
complex_array = np.array([[1,2],[3,4]],dtype=complex)
complex_array

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## Numpy allows to create array with all zeros and ones

In [11]:
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Python provides native range(). Similarly, numpy provides arange(). 

In [12]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [13]:
a = np.arange(0,5,2)
a

array([0, 2, 4])

## linspace() allows to get a numpy array of linearly spaced elements between two numbers. 
## linspace(start,end,no_of_elements)

In [14]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Reshape array

In [16]:
two_dim_array.shape

(2, 3)

In [17]:
two_dim_array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Sometimes while tinktering with data, we want to convert the numpy array to 1D array. Numpy provides two functions ravel() and flatten().
## [here](https://www.linkedin.com/pulse/numpy-difference-between-flatten-raveal-yeshwanth-n/) is the main deference between these two functions

In [18]:
two_dim_array.ravel()

array([1, 2, 3, 4, 5, 6])

In [19]:
two_dim_array.flatten()

array([1, 2, 3, 4, 5, 6])

In [20]:
two_dim_array

array([[1, 2, 3],
       [4, 5, 6]])

## numpy supports basic operations on array like min,max and sum of array

In [21]:
two_dim_array.min()

1

In [22]:
two_dim_array.max()

6

In [23]:
# axis 0 returns sum of all elements on column side. As we have (2,3) array, 
# we will get an array with 3 elements of summation of elements on column side
two_dim_array.sum(axis=0)

array([5, 7, 9])

In [24]:
# axis 1 returns sum of all elements on row side. As we have (2,3) array, 
# we will get an array with 2 elements of summation of elements on row side
two_dim_array.sum(axis=1)

array([ 6, 15])

## Numpy allows mathematical operations on array like sqrt, standard deviation etc. 
https://numpy.org/doc/stable/reference/routines.math.html

## Numpy allows some other operations like summation, multiplying and matrix multiplication as well
## For basic operation of add and etc, the shape of two arrays should be same or the arrays should have similarity of broadcasting

In [25]:
a = np.array([[1,2,3],[5,6,7]])
b= np.array([[5,8,3],[2,3,7]])

In [26]:
a+b

array([[ 6, 10,  6],
       [ 7,  9, 14]])

In [27]:
a-b

array([[-4, -6,  0],
       [ 3,  3,  0]])

In [28]:
a*b

array([[ 5, 16,  9],
       [10, 18, 49]])

In [29]:
a/b

array([[0.2 , 0.25, 1.  ],
       [2.5 , 2.  , 1.  ]])

## Numpy allows operation with scalars as well

In [30]:
a+4

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [31]:
a*6

array([[ 6, 12, 18],
       [30, 36, 42]])

## Let's get an understanding about how Numpy allows operations on [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) similarites of array

In [32]:
a+np.array([1,2,9])

array([[ 2,  4, 12],
       [ 6,  8, 16]])

In [33]:
# This won't be allowed as the shape of [1,2] which is (2,) not broadcastable with (2,3)
# Uncommenting this will give error
# a+np.array([1,2])

# Slicing in numpy

## Numpy allows to access any element of array just like the list in python using index. Also, it supports slicing similar to list like `arr_name[start:stop:step]`

In [34]:
a=np.array([[2,3,5],[5,7,8],[4,9,20]])

In [35]:
a

array([[ 2,  3,  5],
       [ 5,  7,  8],
       [ 4,  9, 20]])

In [36]:
a[1]

array([5, 7, 8])

In [37]:
a[1,2]

8

In [38]:
a[0:2,2]

array([5, 8])

## Traverse through array

In [39]:
for row in a:
    print(row)

[2 3 5]
[5 7 8]
[ 4  9 20]


In [40]:
for cell in a.flat:
    print(cell)

2
3
5
5
7
8
4
9
20


In [41]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
b = np.arange(8,14).reshape(3,2)
b

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [43]:
np.hstack((a,b))

array([[ 1,  2,  8,  9],
       [ 3,  4, 10, 11],
       [ 5,  6, 12, 13]])

In [44]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [45]:
c = np.arange(50).reshape(2,25)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
np.vsplit(c,2)[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
np.vsplit(c,2)[1]

array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
np.hsplit(c,5)

[array([[ 0,  1,  2,  3,  4],
        [25, 26, 27, 28, 29]]),
 array([[ 5,  6,  7,  8,  9],
        [30, 31, 32, 33, 34]]),
 array([[10, 11, 12, 13, 14],
        [35, 36, 37, 38, 39]]),
 array([[15, 16, 17, 18, 19],
        [40, 41, 42, 43, 44]]),
 array([[20, 21, 22, 23, 24],
        [45, 46, 47, 48, 49]])]

## Numpy has a beautiful feature to index using boolean

In [49]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
d=a>3

In [51]:
d

array([[False, False],
       [False,  True],
       [ True,  True]])

In [52]:
a[d]

array([4, 5, 6])

## So what happens here, we created an array d with the boolean values where the value of array a is > 3. and we printed a[d] 

# Iteration in numpy using 

### Numpy allows iterating through array in various methods. Let's understand first the normal loop approach

In [53]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [54]:
for row in a:
    print(row)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]


In [55]:
# in this approach to print the respective values, we'll have to run two loops
for row in a:
    for cell in row :
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [56]:
# To iterate through the loop, we can use  flatten() or ravel() which allows us to iterate through the arrays. However there are fundamental differences : 
# Ref: https://stackoverflow.com/questions/30523123/when-to-use-flat-flatiter-or-flatten
# Ref:https://www.geeksforgeeks.org/differences-flatten-ravel-numpy/

In [57]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


## Using [nditer](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html)

## nditer allows iteration in 2 formats : 
## 1. C order (row by row)
## 2 Fortan order (column by column)

In [58]:
for cell in np.nditer(a, order="c"):
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [59]:
for cell in np.nditer(a, order="f"):
    print(cell)

0
6
1
7
2
8
3
9
4
10
5
11


## nditer also allows to iterate through multiple arrays if their broadcasting is similar